title: Jacopo's brainwaves
author:
  name: Jacopo Margutti
  email: your-email@domain.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: auto

  # nav_pages:
  #   - about.md

  show_excerpts: false

  date_format: "%Y-%m-%d"

  social_links:
    - title: Jacopo on GitHub
      icon: github
      url: "https://github.com/jmargutt"
    - title: Jacopo on Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/jmargutti"
