title: Bapo see, bapo do
author:
  name: Jacopo Margutti

description: >
  Random thoughts.

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: auto

  # nav_pages:
  #   - about.md

  show_excerpts: false

  date_format: "%Y-%m-%d"

  social_links:
    - title: Jacopo on GitHub
      icon: github
      url: "https://github.com/jmargutt"
    - title: Jacopo on Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/jmargutti"
